# Taller 2 - Python
## Fundamentos en Biología Computacional
## 2019-1, Prof. Javier Correa
Nota: Se calificará que el código sea lo más simple, claro, original y eficiente. No usar funciones no realizadas por ustedes mismos.

1. Realice un función para expresar cualquier número entero en su conotación factorial. <br>
Ejemplo: factorial(4)<br>
Out: 24

In [14]:
def factorial(numero):
    f=1
    n=1
    while (n<=numero):
        f=f*n
        n=n+1
    return f


In [2]:
print(factorial(4))

24


2. Realice un función para expresar la potencia de cualquier número. La función recibe como parámetros la base y el exponencial. <br>
Ejemplo: potencia(4,2)<br>
Out: 16

In [9]:
def potencia(n,p):
    return n**p #donde n es la base y p el exponente 

    

In [10]:
print(potencia(3,4)) 

81


3. Utilizando las dos funciones anteriormente definidas (factorial y potencia), realice un función para expresar el Coseno de un entero. <br>
Ejemplo: coseno(5)<br>
Out: 0.996194698

In [15]:
import math
def coseno(numero):
    cose=1
    i=1
    numero = (numero*math.pi)/180
    while (i<=20):
        cose = cose + ((potencia (-1, i)* potencia(numero,2*i))/ factorial(2*i))
        i = i + 1
    return cose

In [16]:
print(coseno(5))

0.9961946980917454


4. Dadas las cantidades de individuos con los genótipos AA, AB y BB. Calcular la frecuencia de los alelos A y B <br>
Ejemplo: FrecuenciaAlelos(12,4,4) <br>
Out: (0.7, 0.3)

In [37]:
def FrecuenciaAlelica(AA,AB,BB):
    a1=AA/(AA+AB+BB)
    b1=AB/(AA+AB+BB)
    c1=BB/(AA+AB+BB)
    alelo1=a1+b1/2
    alelo2=c1+b1/2
    return (alelo1,alelo2)

In [38]:
print(FrecuenciaAlelica(400,400,200))

(0.6000000000000001, 0.4)


5. Dada una cadena de DNA retornar una de (-) RNA en sentido 5'-> 3' <br>
Ejemplo: DNA_to_RNA("TCTCTACTCATGTCTGCA")<br>
Out: GUACUCACGUCUGCUCUC

In [39]:
def DNA_to_RNA(cadena):
    return (cadena.replace("T","U"))

In [40]:
print(DNA_to_RNA("TCTCTACTCATGTCTGCA"))

UCUCUACUCAUGUCUGCA


6. Realizar una función que calcule la Temperatura de Melting Promedio de un par de primers de DNA en grados Celcius. Teniendo en cuenta que; en un oligonucleótido < de 14 nucleótidos, la Tm se calcula multiplicando la cantidad de G+C por 4 y las A+T por 2. Mientras que, si es >= de 14 nt, se debe aplicar la siguiente fórmula (64.9 + 41 * (totalG+C -16.4) / Tamaño sel oligo). <br>
Ejemplo: tempromelt(TCTCTACTCATGTCTGCA, TCGCGTGCACGTG)<br>
Out: 44.88333333333334

In [2]:
def tempromelt(cadena):
    G=0
    C=0
    A=0
    T=0
    i=0
    temperatura=0
    while (i<len(cadena)):
        if (cadena[i]=='G'):
            G=G+1
        elif (cadena[i]=='C'):
            C=C+1
        elif (cadena[i]=='A'):
            A=A+1
        elif (cadena[i]=='T'):
            T=T+1
        i=i+1
    if (len(cadena)<14):
        temperatura=(4*(G+C))+(2*(A+T))
    elif (len(cadena)>=14):
        temperatura= (64.9+41*((G+C)-16.4)/len(cadena))
    return temperatura       
        
        

In [3]:
def tempeoligo(oligo1,oligo2):
    oligo1=tempromelt(oligo1)
    oligo2=tempromelt(oligo2)
    return((oligo1+oligo2)/2)

In [4]:
print(tempeoligo("TCTCTACTCATGTCTGCA","TCGCGTGCACGTG"))

44.88333333333334


7. Hallar la distancia Hamming entre dos secuencias dadas de polipéptidos. <br>
link: https://es.wikipedia.org/wiki/Distancia_de_Hamming <br>
Ejemplo: distancia_Hamming("SRSLLLRFLMSRSLLLRFLLFLLLLPPLPLFLLLLPPL","SRSLLLRFLSSRSLLLRFLLFLLLLAALALFLLLLSML")<br>
Out:6

In [36]:
def distancia_Hamming(poliA,poliB):
    if (len(poliA)==len(poliB)):
        cont=0
        i=0
        while i<len(poliA):
            if (poliA[i] != poliB[i]):
                cont=cont+1
            i=i+1
    return cont


In [37]:
print(distancia_Hamming("SRSLLLRFLMSRSLLLRFLLFLLLLPPLPLFLLLLPPL","SRSLLLRFLSSRSLLLRFLLFLLLLAALALFLLLLSML"))

6


8. Dada la tabla de codones estandar, hacer una función para traducir una cadena de DNA empezando desde la posición 1 <br>
Ejemplo: traducir("ATGGCGCGTATGAATAGCAATCCGAGCGCATGCCATGTTTGCCATGCGGCTCTGGCGGTCATTGATGCGTGCAATAACAATACCCGTAATAGCAATATCAATAGCTAA")<br>
Out: Met A R Met N S N P S A C H V C H A A L A V I D A C N N N T R N S N I N S Stop

In [84]:
diccionario = { "AAA":"K", "AAC":"N", "AAG":"K", "AAU":"N",
                "ACA":"T", "ACC":"T", "ACG":"T", "ACU":"T",
                "AGA":"R", "AGC":"S", "AGG":"R", "AGU":"S",
                "AUA":"I", "AUC":"I", "AUG":"Met", "AUU":"I",

                "CAA":"Q", "CAC":"H", "CAG":"Q", "CAU":"H",
                "CCA":"P", "CCC":"P", "CCG":"P", "CCU":"P",
                "CGA":"R", "CGC":"R", "CGG":"R", "CGU":"R",
                "CUA":"L", "CUC":"L", "CUG":"L", "CUU":"L",

                "GAA":"E", "GAC":"D", "GAG":"E", "GAU":"D",
                "GCA":"A", "GCC":"A", "GCG":"A", "GCU":"A",  
                "GGA":"G", "GGC":"G", "GGG":"G", "GGU":"G",  
                "GUA":"V", "GUC":"V", "GUG":"V", "GUU":"V",  

                "UAA":"Stop", "UAC":"Y", "UAG":"Stop", "UAU":"Y",   
                "UCA":"S", "UCC":"S", "UCG":"S", "UCU":"S",         
                "UGA":"Stop", "UGC":"C", "UGG":"W", "UGU":"C",      
                "UUA":"L", "UUC":"F", "UUG":"L", "UUU":"F"}     
def translate(cadena):
    new_cadena= (cadena.replace("T","U"))
    i=0
    resultado=""
    while (i<len(new_cadena)):
        if ((len(new_cadena) - i)< 3):
            return resultado
        new_cadena1=new_cadena[i]+new_cadena[i+1]+new_cadena[i+2]
        resultado=resultado+diccionario[new_cadena1]+ " "
        i=i+3
    return resultado
        
            
    

In [85]:
print(translate("ATGGCGCGTATGAATAGCAATCCGAGCGCATGCCATGTTTGCCATGCGGCTCTGGCGGTCATTGATGCGTGCAATAACAATACCCGTAATAGCAATATCAATAGCTAA"))

Met A R Met N S N P S A C H V C H A A L A V I D A C N N N T R N S N I N S Stop 


9. Usando la función anterior, traducir la secuencia de DNA dada en los 6 frames posibles para producir un polipéptido.
Ejemplo: traducirALL("ATGGCGCGTATGAATAGCAATCCGAGCGCATGCCATGTTTGCCATGCGGCTCTGGCGGTCATTGATGCGTGCAATAACAATACCCGTAATAGCAATATCAATAGCTAA")<br>
Out: (Frame1:Met A R Met N S N P S A C H V C H A A L A V I D A C N N N T R N S N I N S Stop, Frame2:W R V Stop I A I R A H A Met F A Met R L W R S L Met R A I T I P V I A I S I A, Frame3:G A Y E Stop Q S E R Met P C L P C G S G G H Stop C V Q Stop Q Y P Stop Stop Q Y Q Stop L, Frame4:L A I D I A I T G I V I A R I N D R Q S R Met A N Met A C A R I A I H T R H, Frame5:Stop L L I L L L R V L L L H A S Met T A R A A W Q T W H A L G L L F I R A, Frame6:S Y Stop Y C Y Y G Y C Y C T H Q Stop P P E P H G K H G Met R S D C Y S Y A P)

In [106]:
def traducirALL(cadena):
    RNA=cadena.replace("A","U")
    RNA=RNA.replace("T","A")
    RNA=RNA.replace("C","M")
    RNA=RNA.replace("G","C")
    RNA=RNA.replace("M","G")
    RNA = RNA[::-1]
    i=0
    resultado= ""
    while (i<6):
        if (i<3):
            resultado=resultado+"Frame"+ str(i+1)+ ":" + (translate(cadena))+ ","
            cadena=cadena[1:]
        else:
            resultado=resultado+"Frame"+ str(i+1)+ ":" + (translate(RNA)) + ","
            RNA = RNA [1:]
        i= i+1
    return resultado 


In [107]:
print(traducirALL("ATGGCGCGTATGAATAGCAATCCGAGCGCATGCCATGTTTGCCATGCGGCTCTGGCGGTCATTGATGCGTGCAATAACAATACCCGTAATAGCAATATCAATAGCTAA"))

Frame1:Met A R Met N S N P S A C H V C H A A L A V I D A C N N N T R N S N I N S Stop ,Frame2:W R V Stop I A I R A H A Met F A Met R L W R S L Met R A I T I P V I A I S I A ,Frame3:G A Y E Stop Q S E R Met P C L P C G S G G H Stop C V Q Stop Q Y P Stop Stop Q Y Q Stop L ,Frame4:L A I D I A I T G I V I A R I N D R Q S R Met A N Met A C A R I A I H T R H ,Frame5:Stop L L I L L L R V L L L H A S Met T A R A A W Q T W H A L G L L F I R A ,Frame6:S Y Stop Y C Y Y G Y C Y C T H Q Stop P P E P H G K H G Met R S D C Y S Y A P ,


In [38]:
import numpy as np
def MatrizFrecuencia(lis=[]):
    col = lis[0]
    col = len(col)
    i=0
    pos=0
    conA=0
    conC=0
    conG=0
    conT=0
    matriz = np.zeros((4,col))
    while (i<col):
        while (pos<len(lis)):
            cadena = lis[pos]
            if (cadena[i]=='A'):
                conA = conA + 1
            elif (cadena[i]=='C'):
                conC = conC + 1
            elif (cadena[i]=='G'):
                conG = conG + 1
            elif (cadena[i]=='T'): 
                conT = conT + 1
            pos = pos +1
        matriz[0][i]=conA
        matriz[1][i]=conC
        matriz[2][i]=conG
        matriz[3][i]=conT
        i = i +1
        pos=0
        conA=0
        conC=0
        conG=0
        conT=0
    return matriz
            
        

In [32]:
print(MatrizFrecuencia(["ACTGA", "CCAGA", "AGAGA", "CGTAA"]))

[[2. 0. 2. 1. 4.]
 [2. 2. 0. 0. 0.]
 [0. 2. 0. 3. 0.]
 [0. 0. 2. 0. 0.]]


In [42]:
def mayor (matriz = []):
    mayor0 =  (matriz[0][0])
    mayor1 =  (matriz[0][1])
    mayor2 =  (matriz[0][2])
    mayor3 =  (matriz[0][3])
    L0 = "A"
    L1 = "A"
    L2 = "A"
    L3 = "A"
    cont0 = 1
    cont1 = 1
    cont2 = 1
    cont3 = 1
    i = 0
    j = 1
    while (i < len(matriz)):
        while (j < len (matriz[i])):
            if (i == 0):
                if (mayor0 < matriz[j][i]):
                    mayor0 = matriz[j][i]
                    cont0 = 1
                    if (j==1):
                        L0 = "C"
                    elif (j == 2):
                        L0 = "G"
                    else:
                        L0 = "T"
                elif (mayor0 == matriz[j][i]):
                    mayor0 = mayor0 + matriz[j][i]
                    cont0 = cont0 +1
                    if(j==1):
                        L0 = L0 + ", C"
                    elif(j==2):
                        L0 = L0 + ", G"
                    else:
                        L0 = L0 + ", T"
            if (i == 1):
                if (mayor1 < matriz[j][i]):
                    mayor1 = matriz[j][i]
                    cont1 = 1
                    if (j==1):
                        L1 = "C"
                    elif (j == 2):
                        L1= "G"
                    else:
                        L1 = "T"
                elif (mayor1 == matriz[j][i]):
                    mayor1 = mayor1 + matriz[j][i]
                    cont1 = cont1 +1
                    if(j==1):
                        L1 = L1 + ", C"
                    elif(j==2):
                        L1 = L1 + ", G"
                    else:
                        L1 = L1 + ", T"
            if (i == 2):
                if (mayor2 < matriz[j][i]):
                    mayor2 = matriz[j][i]
                    cont2 = 1
                    if (j==1):
                        L2 = "C"
                    elif (j == 2):
                        L2= "G"
                    else:
                        L2 = "T"
                elif (mayor2 == matriz[j][i]):
                    mayor2 = mayor2 + matriz[j][i]
                    cont2 = cont2 +1
                    if(j==1):
                        L2 = L2 + ", C"
                    elif(j==2):
                        L2 = L2 + ", G"
                    else:
                        L2 = L2 + ", T"
            if (i == 3):
                if (mayor3 < matriz[j][i]):
                    mayor3 = matriz[j][i]
                    cont3 = 1
                    if (j==1):
                        L3 = "C"
                    elif (j == 2):
                        L3= "G"
                    else:
                        L3 = "T"
                elif (mayor3 == matriz[j][i]):
                    mayor3 = mayor3 + matriz[j][i]
                    cont3 = cont3 +1
                    if(j==1):
                        L3 = L3 + ", C"
                    elif(j==2):
                        L3 = L3 + ", G"
                    else:
                        L3 = L3 + ", T"
            j = j +1
        j = 1
        i = i+1
    Rmayor0 = (str ((mayor0/cont0)/len(matriz))+ "  ")*cont0 + "En " + L0
    Rmayor1 = (str((mayor1/cont1)/len(matriz)) + "  ")*cont1 + "En " + L1
    Rmayor2 = (str((mayor2/cont2)/len(matriz))+ "  ")*cont2  + "En "  + L2
    Rmayor3 = (str((mayor3/cont3)/len(matriz))+ "  ")*cont3  + "En "  + L3
    matrizR = [Rmayor0, Rmayor1, Rmayor2, Rmayor3]
    return matrizR

In [45]:
print(mayor(MatrizFrecuencia(["ACTG", "CCAG", "AGAG", "CGTA"])))

['0.5  0.5  En A, C', '0.5  0.5  En C, G', '0.5  0.5  En A, T', '0.75  En G']
