# Taller 2 - Python
## Fundamentos en Biología Computacional
## 2019-1, Prof. Javier Correa
Nota: Se calificará que el código sea lo más simple, claro, original y eficiente. No usar funciones no realizadas por ustedes mismos.

1. Realice un función para expresar cualquier número entero en su conotación factorial. <br>
Ejemplo: factorial(4)<br>
Out: 24

In [32]:
def numero_factorial(numero):
    i= 1
    multi=1
    while i <= numero:
        multi=multi*i
        i=i+1
    
    return multi
    
numero_factorial(3)

6

2. Realice un función para expresar la potencia de cualquier número. La función recibe como parámetros la base y el exponencial. <br>
Ejemplo: potencia(4,2)<br>
Out: 16

In [33]:
def num_elevado(base, exponente):

    result= base**exponente
    return result
num_elevado(2,3)


8

3. Utilizando las dos funciones anteriormente definidas (factorial y potencia), realice un función para expresar el Coseno de un entero. <br>
Ejemplo: coseno(5)<br>
Out: 0.996194698

In [56]:
def coseno(x):
    xg=(3.1416/180)*x 
    sumatoria=0
    i=0
    total=0
    while i <= 20:
        sumatoria=((-1)**i)*(num_elevado(xg,2*i)/(numero_factorial(2*i)))
        i=i+1
        total=total+sumatoria
    return total
coseno(5)
                       
                       
                       
                                 

0.9961946803061181

4. Dadas las cantidades de individuos con los genótipos AA, AB y BB. Calcular la frecuencia de los alelos A y B <br>
Ejemplo: FrecuenciaAlelos(12,4,4) <br>
Out: (0.7, 0.3)

In [43]:
def f_alelica(AA, AB,BB):
    
    poblacion= AA+AB+BB
    mitad= (AB/poblacion)/2
    F_AA= AA/poblacion + mitad
    F_BB= BB/poblacion + mitad
    alelos= [F_AA,F_BB]
    return alelos
f_alelica(12,4,4)

[0.7, 0.30000000000000004]

5. Dada una cadena de DNA retornar una de (-) RNA en sentido 5'-> 3' <br>
Ejemplo: DNA_to_RNA("TCTCTACTCATGTCTGCA")<br>
Out: GUACUCACGUCUGCUCUC

In [213]:
def DNA_to_RNA(DNA):
    RNA=DNA 
    RNA=RNA.replace('T','U') 
    invRNA=''
    RNA_=''
    x=0
       
    while x<=len(RNA)-1:
        if RNA[x]=='U':
            invRNA=invRNA+'A'
        if RNA[x]=='C':
            invRNA=invRNA+'G'
        if RNA[x]=='A':
            invRNA=invRNA+'U'
        if RNA[x]=='G':
            invRNA=invRNA+'C'
        x=x+1
        RNA_=invRNA[::-1]
        
    
    return RNA_

DNA_to_RNA('TCTCTACTCATGTCTGCA')
    


'UGCAGACAUGAGUAGAGA'

6. Realizar una función que calcule la Temperatura de Melting Promedio de un par de primers de DNA en grados Celcius. Teniendo en cuenta que; en un oligonucleótido < de 14 nucleótidos, la Tm se calcula multiplicando la cantidad de G+C por 4 y las A+T por 2. Mientras que, si es >= de 14 nt, se debe aplicar la siguiente fórmula (64.9 + 41 * (totalG+C -16.4) / Tamaño sel oligo). <br>
Ejemplo: tempromelt(TCTCTACTCATGTCTGCA, TCGCGTGCACGTG)<br>
Out: 44.88333333333334

In [6]:
def tm_promedio(primer1, primer2):
   
    G1=0 ; G2=0 ; i=0 ; x=0   
    C1=0 ; C2=0 ; tm_primer1corto=0 ; tm_primer2largo=0
    T1=0 ; T2=0 ; tm_primer1largo=0 ; tm_final_primer1=0
    A1=0 ; A2=0 ; tm_primer2corto=0 ; tm_final_primer2=0
    
    while i<=len(primer1)-1:
        if primer1[i]=='G':
            G1= G1 + 1
        if primer1[i]=='C':
            C1= C1 + 1
        if primer1[i]=='T':
            T1= T1 + 1
        if primer1[i]=='A':
            A1= A1 + 1
        i=i+1
        
    x=0
    while x<=len(primer2)-1:
        if primer2[x]=='G':
            G2= G2 + 1
        if primer2[x]=='C':
            C2= C2 + 1
        if primer2[x]=='T':
            T2= T2 + 1
        if primer2[x]=='A':
            A2= A2 + 1
        x=x+1
    
    if len(primer1)<14:
        tm_primer1corto = ((C1+G1)*4)+((T1+A1)*2)
        tm_final_primer1 = tm_primer1corto
        
    if len(primer1)>=14:
        tm_primer1largo = (64.9 + 41 * ((G1+C1) -16.4) /len(primer1))
        tm_final_primer1 = tm_primer1largo
    
    
    if len(primer2)<14:
        tm_primer2corto = ((C2+G2)*4)+((T2+A2)*2)
        tm_final_primer2 = tm_primer2corto
                          
    if len(primer2)>=14:
        tm_primer2largo = (64.9 + 41 * ((G2+C2) -16.4) /len(primer2))
        tm_final_primer2 =tm_primer2largo
    
    return (tm_final_primer1 + tm_final_primer2)/2
                          
tm_promedio("TCTCTACTCATGTCTGCA" , "TCGCGTGCACGTG")  

44.88333333333334

7. Hallar la distancia Hamming entre dos secuencias dadas de polipéptidos. <br>
link: https://es.wikipedia.org/wiki/Distancia_de_Hamming <br>
Ejemplo: distancia_Hamming("SRSLLLRFLMSRSLLLRFLLFLLLLPPLPLFLLLLPPL","SRSLLLRFLSSRSLLLRFLLFLLLLAALALFLLLLSML")<br>
Out:6

In [7]:
def distancia_hamming(poliA, poliB):
    i=0 ; y=0
    suma=0
    while i <=len(poliA)-1 and y <=len(poliB)-1:
        
        if poliA[i]!=poliB[y]:
            suma= suma + 1

        if poliA[i]==poliB[y]:
            suma=suma
            
        i=i+1
        y=y+1
        
    return suma
distancia_hamming("SRSLLLRFLMSRSLLLRFLLFLLLLPPLPLFLLLLPPL","SRSLLLRFLSSRSLLLRFLLFLLLLAALALFLLLLSML") 

6

8. Dada la tabla de codones estandar, hacer una función para traducir una cadena de DNA empezando desde la posición 1 <br>
Ejemplo: traducir("ATGGCGCGTATGAATAGCAATCCGAGCGCATGCCATGTTTGCCATGCGGCTCTGGCGGTCATTGATGCGTGCAATAACAATACCCGTAATAGCAATATCAATAGCTAA")<br>
Out: Met A R Met N S N P S A C H V C H A A L A V I D A C N N N T R N S N I N S Stop

In [115]:
codones={}
codones['UUU']='phe'
codones['UUC']='phe'
    
codones['UUA']='leu'
codones['UUG']='leu'
codones['CUU']='leu'
codones['CUC']='leu'
codones['CUA']='leu'
codones['CUG']='leu'
    
codones['AUU']='ile'
codones['AUC']='ile'
codones['AUA']='ile'
    
codones['AUG']="met"
    
codones['GUU']='val'
codones['GUC']='val'
codones['GUA']='val'
codones['GUG']='val'
    
codones['AGC']='ser'
codones['UCU']='ser'
codones['UCC']='ser'
codones['UCA']='ser'
codones['UCG']='ser'
codones['AGU']='ser'
    
codones['CCU']='pro'
codones['CCC']='pro'
codones['CCA']='pro'
codones['CCG']='pro'
      
codones['ACU']='thr'
codones['ACC']='thr'
codones['ACA']='thr'
codones['ACG']='thr'
    
codones['GCU']='ala'
codones['GCC']='ala'
codones['GCA']='ala'
codones['GCG']='ala'

codones['UAU']='tyr'
codones['UAC']='tyr'
    
codones['UAA']='stop'
codones['UAG']='stop'
codones['UGA']='stop'
    
codones['CAU']='his'
codones['CAC']='his'
    
codones['CAA']='gln'
codones['CAG']='gln'
    
codones['AAU']='asn'
codones['AAC']='asn'
    
codones['AAA']='lys'
codones['AAG']='lys'
    
codones['GAU']='asp'
codones['GAC']='asp'

codones['GAA']='glu'
codones['GAG']='glu'
    
codones['UGU']='cys'
codones['UGC']='cys'
    
codones['UGG']='trp'
    
codones['CGU']='arg'
codones['CGC']='arg'
codones['CGA']='arg'
codones['CGG']='arg'
codones['AGA']='arg'
codones['AGG']='arg'

    
codones['GGU']='gly'
codones['GGC']='gly'
codones['GGA']='gly'
codones['GGG']='gly'


In [124]:
def traducir(DNA):
    RNA=DNA 
    RNA=RNA.replace('T','U') #lo más útil de la vida
    a_a=""; x=0
    while x<=len(RNA)-2:
        try: #la segunda mejor funcion
            a_a+=str((codones[RNA[x:x+3]]))+" "
            x=x+3
        except:
            pass
    return a_a 
 

      
traducir('ATGGCGCGTATGAATAGCAATCCGAGCGCATGCCATGTTTGCCATGCGGCTCTGGCGGTCATTGATGCGTGCAATAACAATACCCGTAATAGCAATATCAATAGCTAA')


'met ala arg met asn ser asn pro ser ala cys his val cys his ala ala leu ala val ile asp ala cys asn asn asn thr arg asn ser asn ile asn ser stop '

9. Usando la función anterior, traducir la secuencia de DNA dada en los 6 frames posibles para producir un polipéptido.
Ejemplo: traducirALL("ATGGCGCGTATGAATAGCAATCCGAGCGCATGCCATGTTTGCCATGCGGCTCTGGCGGTCATTGATGCGTGCAATAACAATACCCGTAATAGCAATATCAATAGCTAA")<br>
Out: (Frame1:Met A R Met N S N P S A C H V C H A A L A V I D A C N N N T R N S N I N S Stop, Frame2:W R V Stop I A I R A H A Met F A Met R L W R S L Met R A I T I P V I A I S I A, Frame3:G A Y E Stop Q S E R Met P C L P C G S G G H Stop C V Q Stop Q Y P Stop Stop Q Y Q Stop L, Frame4:L A I D I A I T G I V I A R I N D R Q S R Met A N Met A C A R I A I H T R H, Frame5:Stop L L I L L L R V L L L H A S Met T A R A A W Q T W H A L G L L F I R A, Frame6:S Y Stop Y C Y Y G Y C Y C T H Q Stop P P E P H G K H G Met R S D C Y S Y A P)

In [134]:
def frames (DNA):
    RNA=DNA 
    RNA=RNA.replace('T','U')
    x=0
    a_1='' ; a_2='' ; a_3='' ; a_4='' ; a_5='' ; a_6=''
    a_total='Frame 1:   '    
    while x<=len(RNA)-2:
        try:
            a_1=str((codones[RNA[x:x+3]]))+' '
            a_total+=a_1
            x=x+3
        except:
            pass
    x=1
    a_total+='Frame2:   '
    while x<=len(RNA)-2:
        try:
            a_2=str((codones[RNA[x:x+3]]))+' '
            a_total+=a_2
            x=x+3
        except:
            x=x+3
            pass
    x=2
    a_total+='Frame3:   '
    while x<=len(RNA)-2:
        try:
            a_3=str((codones[RNA[x:x+3]]))+' '
            a_total+=a_3
            x=x+3
        except:
            x=x+3
            pass
        
    RNA_=RNA[::-1]
    x=0
    a_total+='Frame4:   '
    while x<=len(RNA_)-2:
        try:
            a_4=str((codones[RNA_[x:x+3]]))+' '
            a_total+=a_4
            x=x+3
        except:
            x=x+3
            pass
        
    RNA_=RNA[::-1]
    x=1
    a_total+='Frame5:   '
    while x<=len(RNA_)-2:
        try:
            a_5=str((codones[RNA_[x:x+3]]))+' '
            a_total+=a_5
            x=x+3
        except:
            x=x+3
            pass
        
    RNA_=RNA[::-1]
    x=2
    a_total+='Frame6:   '
    while x<=len(RNA_)-2:
        try:
            a_6=str((codones[RNA_[x:x+3]]))+' '
            a_total+=a_6
            x=x+3
        except:
            x=x+3
            pass
    
    return a_total



frames('ATGGCGCGTATGAATAGCAATCCGAGCGCATGCCATGTTTGCCATGCGGCTCTGGCGGTCATTGATGCGTGCAATAACAATACCCGTAATAGCAATATCAATAGCTAA')  

'Frame 1:   met ala arg met asn ser asn pro ser ala cys his val cys his ala ala leu ala val ile asp ala cys asn asn asn thr arg asn ser asn ile asn ser stop Frame2:   trp arg val stop ile ala ile arg ala his ala met phe ala met arg leu trp arg ser leu met arg ala ile thr ile pro val ile ala ile ser ile ala Frame3:   gly ala tyr glu stop gln ser glu arg met pro cys leu pro cys gly ser gly gly his stop cys val gln stop gln tyr pro stop stop gln tyr gln stop leu Frame4:   asn arg stop leu stop arg stop cys pro stop gln stop arg ala stop leu leu ala val ser ala tyr arg leu tyr arg thr arg ala stop arg stop val cys ala val Frame5:   ile asp asn tyr asn asp asn ala his asn asn asn val arg ser tyr trp arg ser arg arg thr val cys thr val arg glu pro asn asp lys tyr ala arg Frame6:   ser ile thr ile thr ile met pro ile thr ile thr cys val val thr gly gly leu gly val pro phe val pro tyr ala ser leu thr ile ser met arg gly '

10. Su código genético es esencialmente el mismo desde que nace hasta que muere, y el mismo en su sangre y su cerebro. Los genes que se activan y desactivan marcan la diferencia entre las células. Esta regulación de los genes está orquestada por un mecanismo inmensamente complejo, que solo hemos empezado a comprender. Una parte central de este mecanismo consiste en moléculas llamadas factores de transcripción que se adhieren al ADN, y al hacerlo, activan o desactivan los genes cercanos. Estas moléculas se unen preferentemente a secuencias específicas de ADN, y este patrón de preferencia de unión puede representarse mediante una tabla de frecuencias de símbolos dados en cada posición del patrón. Más precisamente, cada fila en la tabla corresponde a las bases A, C, G y T, mientras que la columna j refleja cuántas veces aparece la base en la posición j en la secuencia del ADN.

    Por ejemplo; si nuestro conjunto de secuencias de ADN son TAG, GGT y GGG, la tabla se convierte en


|base|	0|	1|	2|
|----|---|---|---|
|A	|0	|1	|0  |
|C	|0	|0	|0  |
|G 	|2	|2	|2  |
|T	|1	|0	|1  |

De esta tabla podemos leer que la base A aparece una vez en el índice 1 en las cadenas de ADN, la base C no aparece en absoluto, la base G aparece dos veces en todas las posiciones y la base T aparece una vez al principio y al final de las cadenas.

a. Dada una lista de Strings con motivos de 4 nucleótidos, construir una matriz de frecuencias para las posiciones de los 4 nucleótidos. 

Ejemplo:<br>
listamotivos =["ACTG", "CCAG", "AGAG", "CGTA"]<br>
MatrizFrecuencia(listamotivos)<br>
Out: [[2, 0, 2, 1]<br>
 [2, 2, 0, 0]<br>
 [0, 2, 0, 3]<br>
 [0, 0, 2, 0]]<br>
 
b. Realizar una función que retorne el nucleótido que más frecuencia obtuvo por posición. Si tienen la misma frecuecia retornar los valores iguales. <br>
Ejemplo:<br>
FrecuenciaMayorNt(MatrizFrecuencia(listamotivos))<br>
Out: [[A:0.5, C:0.5],<br>
[C:0.5,G:0.5],<br>
[A:0.5,T:0.5],<br>
[G:0.75]]<br>

## Javi lo intente demasiado pero no fui capaz, podrías resolverlo en la proxima clase, gracias.

In [273]:

import numpy
def datos(DNA):
    results = numpy.zeros((len(DNA), len(DNA)))
    i=0
    j=0
    C=["A","C","G","T"]
    while i<len((DNA[0])[0]):
        while j<len(DNA):
            if((DNA[j])[i])==C[i]:
                results[i][j]=results[i][j]+1
            j=j+1
        i=i+1
        j=0    
    print(results) 
datos(["ACTG", "CCAG", "AGAG", "CGTA"])

[[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [257]:
import numpy
def datos(DNA):
    #i=0 ; y=0 ;
    #results = numpy.zeros((len(datos), len(datos)))
    sumaA=0
    #sumaT=0
    #sumaC=0
    #sumag=0
    
    if len((DNA[0])[0]) or len((DNA[0])[1]) or len((DNA[0])[2]) or len((DNA[0])[3])== 'A':
        sumaA+=1
       # if results[i][y] == len((DNA[0])[0]) or len((DNA[0])[1]) or len((DNA[0])[2]) or len((DNA[0])[3])== 'A':
        #results[i][y]=suma
    #return results
        
    #if results[-1][-1] == 0:
        

    
    
    #i=i+1
    #y=y+1
    print(suma)         
             
datos(["ACTG", "CCAG", "AGAG", "CGTA"])

NameError: name 'suma' is not defined

In [223]:
datos=["ACTG", "CCAG", "AGAG", "CGTA"]
type(datos)
print ((datos[0])[0])



A


In [186]:
datos=["ACTG", "CCAG", "AGAG", "CGTA"]
len(datos)
jiji=numpy.zeros((len(datos), len(datos)))
print(jiji)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
