# Taller 2 - Python
    Fundamentos en Biología Computacional
    por: Juliana Madrigal Vélez

1. Realice un función para expresar cualquier número entero en su conotación factorial. 
Ejemplo: factorial(4)
Out: 24

In [92]:
def factorial(numero): 
    i = 1
    factorial = numero
    while i < numero:
        factorial = factorial * i
        i = i + 1
    return factorial 

factorial (4)

24

2. Realice un función para expresar la potencia de cualquier número. La función recibe como parámetros la base y el exponencial. 
Ejemplo: potencia(4,2)
Out: 16

In [93]:
def potencia (base, exp):
    resultado = base**exp
    return resultado
potencia (4,2)

16

3. Utilizando las dos funciones anteriormente definidas (factorial y potencia), realice un función para expresar el Seno de un entero. 
Ejemplo: seno(5)
Out: -0.9589331651965962

In [94]:
def seno (numero):
    numero = float (numero)
    aux = 0.0
    for i in range (0,10):
        aux = aux + ((potencia(-1,i))/(factorial(2*i+1)))*(potencia(numero,(2*i+1)))
    return (aux)

seno (5)

-0.9589331651965963

4. Dadas las cantidades de individuos con los genótipos AA, AB y BB. Calcular la frecuencia del alelo A esperada en equilibrio de Hardyweinber. 
Ejemplo: hardyweinbergpp(12,4,4) 
Out: 0.48999999999999994

In [95]:
def hardyweinbergpp(AA,AB,BB):
    
    n = AA+AB+BB
    proporcionA = AA/n
    proporcionAB = AB/n
    proporcionBB = BB/n
    frecuenciadominante = proporcionA + (proporcionAB/2)
    frecuenciarecesivo = 1 - frecuenciadominante
    frecuencia_alelo_recesivo = frecuenciarecesivo ** (1/2)
    frecuencia_alelo_dominante = 1 - frecuencia_alelo_recesivo
    
    return frecuencia_alelo_dominante
    
hardyweinbergpp(12,4,4)

0.4522774424948338

5. Dada una cadena de DNA retornar una de RNA 
Ejemplo: DNA_to_RNA("TCTCTACTCATGTCTGCA")
Out: UCUCUACUCAUGUCUGCA

In [96]:
def DNA_to_RNA(cadena):
    respuesta = ""
    for i in cadena:
        if(i == "T"):
            respuesta += "U"
        else:
            respuesta = respuesta + i
    return respuesta

DNA_to_RNA ("TCTCTACTCATGTCTGCA")

'UCUCUACUCAUGUCUGCA'

6. Realizar una función que calcule la Temperatura de Melting de un primer de DNA en grados Celcius. Teniendo en cuenta que; en un oligonucleótido < de 14 nucleótidos, la Tm se calcula multiplicando la cantidad de G+C por 4 y las A+T por 2. Mientras que, si es >= de 14 nt, se debe aplicar la siguiente fórmula (64.9 + 41 * (totalG+C -16.4) / Tamaño sel oligo). 
Ejemplo: tempmelt(TCTCTACTCATGTCTGCA)
Out: 57.2

In [97]:
def tempmelting (nucleotidos):
    secuencia = nucleotidos
    tamaño_secuencia = len (nucleotidos)
    contarG = 0
    contarC = 0
    contarT = 0
    contarA = 0
    
    for i in secuencia:
    
        if i == "G":
            contarG = contarG + 1
        if i == "C":
            contarC = contarC + 1
        if i == "T":
            contarT = contarT + 1
        if i == "A":
            contarA= contarA + 1

    if tamaño_secuencia < 14:
        Tm = ((contarG + contarC) * 4) + ((contarT + contarA) * 2)
    else:
        Tm = 64.9 + 41 * ((contarG + contarC - 16.4)/tamaño_secuencia)

    return Tm

tempmelting ("TCTCTACTCATGTCTGCA")

45.76666666666668

7. Hallar la distancia Hamming entre dos secuencias de polipéptidos. 
link: https://es.wikipedia.org/wiki/Distancia_de_Hamming 
Ejemplo: distancia_Hamming("SRSLLLRFLMSRSLLLRFLLFLLLLPPLPLFLLLLPPL","SRSLLLRFLSSRSLLLRFLLFLLLLAALALFLLLLSML")
Out:6

In [98]:
def distanciaHamming (secuencia1, secuencia2):
    distancia = 0
    longitud = len (secuencia1)
    for i in range (longitud):
        if secuencia1 [i] != secuencia2[i]:
            distancia = distancia + 1
    return distancia

distanciaHamming ("SRSLLLRFLMSRSLLLRFLLFLLLLPPLPLFLLLLPPL","SRSLLLRFLSSRSLLLRFLLFLLLLAALALFLLLLSML")


6

8. Dada la tabla de codones estandar, hacer una función para traducir una cadena de DNA empezando desde la posición 1 <br>
Ejemplo: traducir("ATGGCGCGTATGAATAGCAATCCGAGCGCATGCCATGTTTGCCATGCGGCTCTGGCGGTCATTGATGCGTGCAATAACAATACCCGTAATAGCAATATCAATAGCTAA")<br>
Out: Met A R Met N S N P S A C H V C H A A L A V I D A C N N N T R N S N I N S Stop

In [99]:
def traduccion(secuencia):
    tabla = {
    'ATA':'I', 'ATC':'I', 'ATT':'I', 'ATG':'Met',
    'ACA':'T', 'ACC':'T', 'ACG':'T', 'ACT':'T',
    'AAC':'N', 'AAT':'N', 'AAA':'K', 'AAG':'K',
    'AGC':'S', 'AGT':'S', 'AGA':'R', 'AGG':'R',
    'CTA':'L', 'CTC':'L', 'CTG':'L', 'CTT':'L',
    'CCA':'P', 'CCC':'P', 'CCG':'P', 'CCT':'P',
    'CAC':'H', 'CAT':'H', 'CAA':'Q', 'CAG':'Q',
    'CGA':'R', 'CGC':'R', 'CGG':'R', 'CGT':'R',
    'GTA':'V', 'GTC':'V', 'GTG':'V', 'GTT':'V',
    'GCA':'A', 'GCC':'A', 'GCG':'A', 'GCT':'A',
    'GAC':'D', 'GAT':'D', 'GAA':'E', 'GAG':'E',
    'GGA':'G', 'GGC':'G', 'GGG':'G', 'GGT':'G',
    'TCA':'S', 'TCC':'S', 'TCG':'S', 'TCT':'S',
    'TTC':'F', 'TTT':'F', 'TTA':'L', 'TTG':'L',
    'TAC':'Y', 'TAT':'Y', 'TAA':'Stop', 'TAG':'Stop',
    'TGC':'C', 'TGT':'C', 'TGA':'Stop', 'TGG':'W',}
    
    proteina = ""
    if len(secuencia)%3 == 0:
        for i in range(0, len(secuencia), 3):
            codon = secuencia[i : i+3]
            proteina += tabla[codon]
    return proteina

translate ("ATGGCGCGTATGAATAGCAATCCGAGCGCATGCCATGTTTGCCATGCGGCTCTGGCGGTCATTGATGCGTGCAATAACAATACCCGTAATAGCAATATCAATAGCTAA")


'MetARMetNSNPSACHVCHAALAVIDACNNNTRNSNINSStop'

9. Usando la función anterior, traducir en los 6 frames una cadena de DNA dada. Ejemplo: traducirALL("ATGGCGCGTATGAATAGCAATCCGAGCGCATGCCATGTTTGCCATGCGGCTCTGGCGGTCATTGATGCGTGCAATAACAATACCCGTAATAGCAATATCAATAGCTAA")
Out: (1:Met A R Met N S N P S A C H V C H A A L A V I D A C N N N T R N S N I N S Stop, 2:W R V Stop I A I R A H A Met F A Met R L W R S L Met R A I T I P V I A I S I A, 3:G A Y E Stop Q S E R Met P C L P C G S G G H Stop C V Q Stop Q Y P Stop Stop Q Y Q Stop L, 4:L A I D I A I T G I V I A R I N D R Q S R Met A N Met A C A R I A I H T R H, 5:Stop L L I L L L R V L L L H A S Met T A R A A W Q T W H A L G L L F I R A, 6:S Y Stop Y C Y Y G Y C Y C T H Q Stop P P E P H G K H G Met R S D C Y S Y A P)

10. Un investigador realizó un experiemento donde trató células cancerígeneas con un antimitótico y luego de un tiempo cuantificó la expresión de varios oncogenes usando RNAseq. (Figura adjunta).<br>
![texte](image.png)
En la imagen se muestra en la primera columna los IDs de los oncogenes. Las tres columnas siguientes (Son réplicas del tratamiento control con células no tratadas, Exp1, Exp2 y Exp3). Las tres últimas columnas son las tres réplicas del tratamiento con el antimitótico. <br>
a. Utilizando la librería numpy, creár una matríz y cargar los datos de la tabla e imprimirla. <br>
b. Realizar una función que promedie, usando las tres réplicas, la expresión de cada gen por tratamiento. <br>
c. Realizar una función donde a partir de los promedio de cada gen, compare el tratamiento versus el control y si la relación es < 0.5 ó > 1.5 retornar el ID del gen expresado diferencialmente.

In [100]:
from numpy import matrix
Tratamiento = matrix ([[3501.2,5697.47,2426.72],[128.67,104.42,101.33],[9.05,23.33,8.44],[750.9,659.84,491.89],[735.82,816.46,118.22],[245.27,372.13,335.67],[17.09,13.33,8.44],[1731.0,1641.81,1853.55],[268.39,186.62,135.11],[323.68,428.78.116.11],[370.93,378.79,279.72],[214.11,168.85,144.61],[30.16,63.32,26.39],[97.51,77.76,71.78],[5209.07,7680.3,6312.2]])
print (Tratamiento)

a = np.mean(control[0:])
b = np.mean(control[1:])
c = np.mean(control[3:])
d = np.mean(control[4:])
e = np.mean(control[5:])
f = np.mean(control[6:])
g = np.mean(control[7:])
h = np.mean(control[8:])
i = np.mean(control[9:])
j = np.mean(control[10:])
k = np.mean(control[11:])
l = np.mean(control[12:])
m = np.mean(control[13:])
n = np.mean(control[14:])


print (a,b,c,d,e,f,g,h,i,j,k,l,m,n)

SyntaxError: invalid syntax (<ipython-input-100-ee4129a5bd17>, line 2)

In [101]:
import numpy as np
from numpy import matrix 
control = matrix([[67540.89,70924.09,80243.76],[811.93,801.36,740.71],[190.41,211.06,236.19],[66.77,57.56,101.09],[3.3,11.29,1.89],[45.34,36.12,51.02],[103.04,370.21,200.29],[7708.78,6976.38,6569.04],[31.32,10.16,24.56],[31.32,24.83,19.84],[47.81,89.17,70.86],[703.95,689.62,662.29],[222.56,339.73,226.75],[12.36,11.29,8.5],[20613.09,25218.13,31540.46]])
print (control)

a = np.mean(control[0:])
b = np.mean(control[1:])
c = np.mean(control[3:])
d = np.mean(control[4:])
e = np.mean(control[5:])
f = np.mean(control[6:])
g = np.mean(control[7:])
h = np.mean(control[8:])
i = np.mean(control[9:])
j = np.mean(control[10:])
k = np.mean(control[11:])
l = np.mean(control[12:])
m = np.mean(control[13:])
n = np.mean(control[14:])


print (a,b,c,d,e,f,g,h,i,j,k,l,m,n)


[[6.754089e+04 7.092409e+04 8.024376e+04]
 [8.119300e+02 8.013600e+02 7.407100e+02]
 [1.904100e+02 2.110600e+02 2.361900e+02]
 [6.677000e+01 5.756000e+01 1.010900e+02]
 [3.300000e+00 1.129000e+01 1.890000e+00]
 [4.534000e+01 3.612000e+01 5.102000e+01]
 [1.030400e+02 3.702100e+02 2.002900e+02]
 [7.708780e+03 6.976380e+03 6.569040e+03]
 [3.132000e+01 1.016000e+01 2.456000e+01]
 [3.132000e+01 2.483000e+01 1.984000e+01]
 [4.781000e+01 8.917000e+01 7.086000e+01]
 [7.039500e+02 6.896200e+02 6.622900e+02]
 [2.225600e+02 3.397300e+02 2.267500e+02]
 [1.236000e+01 1.129000e+01 8.500000e+00]
 [2.061309e+04 2.521813e+04 3.154046e+04]]
7213.358222222222 2521.247142857143 2858.3533333333335 3111.372727272727 3421.960666666667 3797.271851851852 4243.866666666667 3838.028571428572 4474.031111111111 5363.771333333334 6687.394166666668 8688.096666666666 12900.638333333334 25790.559999999998
